version: "3"
services:
  wallabag:
    image: wallabag/wallabag
    restart: unless-stopped
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.wezzit.org
      - SYMFONY__ENV__SERVER_NAME="Sandeep's Wallabag"
    ports:
      - 7780:80
    volumes:
      - /mnt/userdata/docker/wallabag/data:/var/www/wallabag/data:rw
      - /mnt/userdata/docker/wallabag/images:/var/www/wallabag/web/assets/images:rw
    labels:
      traefik.enable: "true"
      traefik.http.routers.wallabag.rule: Host(`wallabag.wezzit.org`)
      traefik.http.routers.wallabag.tls.certresolver: letsencrypt
      traefik.http.routers.wallabag.tls.domains[0].main: wezzit.org
      traefik.http.routers.wallabag.tls.domains[0].sans: "*.wezzit.org"
      traefik.http.services.wallabag.loadbalancer.server.port: "80"
    healthcheck:
      test:
        - CMD
        - wget
        - --no-verbose
        - --tries=1
        - --spider
        - http://localhost
      interval: 1m
      timeout: 3s
networks: {}
