version: "3.8"
services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - /mnt/userdata/docker/hoarder/data:/data
    ports:
      - 9354:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...
      DATA_DIR: /data
    labels:
      - homepage.group=Media
      - homepage.name=Hoarder
      - homepage.icon=hoarder.svg
      - homepage.href=https://bookmarks.wezzit.org
      - homepage.description=Bookmark manager
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.6.2
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data
  ollama:
    image: ollama/ollama
    restart: always
    env_file:
      - .env
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434
volumes:
  meilisearch: null
  ollama: null
networks: {}
