services:
  silverbullet:
    image: ghcr.io/silverbulletmd/silverbullet:v2
    restart: unless-stopped
    env_file: .env
    volumes:
      - /mnt/userdata/notes:/space
    ports:
      - 4726:3000
networks: {}
