services:
  db:
    image: mariadb:10.11
    container_name: seafile-mysql
    restart: unless-stopped    
    env_file: .env
    volumes:
      - /mnt/userdata/docker/seafile/db:/var/lib/mysql # Required, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net
  memcached:
    image: memcached:1.6.18
    container_name: seafile-memcached
    restart: unless-stopped
    entrypoint: memcached -m 256
    networks:
      - seafile-net
  seafile:
    image: seafileltd/seafile-mc:11.0-latest
    container_name: seafile
    restart: unless-stopped
    ports:
      - 6739:80
    #     - "443:443"  # If https is enabled, cancel the comment.
    labels:
      - homepage.group=Documents
      - homepage.name=Seafile
      - homepage.icon=seafile.png
      - homepage.href=https://files.wezzit.org
      - homepage.description=SeaFile file manager
    volumes:
      - /mnt/userdata/docker/seafile/data:/shared # Required, specifies the path to Seafile data persistent store.
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=${MYSQL_ROOT_PASSWORD} # Required, the value should be root's password of MySQL service.
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net
networks:
  seafile-net: null
