# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    labels:
      glance.name: Pi-hole
      glance.icon: si:pihole
      glance.url: http://nasbox.local:5793
      glance.description: Pi-hole DNS server
      glance.id: pihole
    ports:
      # DNS Ports
      - 53:53/tcp
      - 53:53/udp
      # HTTP(S) ports
      - 5793:80/tcp
      #- 443:443/tcp
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
    env_file: .env
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: Europe/London
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - /mnt/userdata/docker/pihole/etc-pihole:/etc/pihole
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped
networks: {}
