---
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/userdata/docker/heimdall/config:/config
    ports:
      - 8080:80
    restart: unless-stopped
