version: "3.2"
services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    volumes:
      - /mnt/userdata/docker/backrest/data:/data
      - /mnt/userdata/docker/backrest/config:/config
      - /mnt/userdata/docker/backrest/cache:/cache
      - /mnt/userdata:/userdata # [optional] mount local paths to backup here.
      - /media/sdb1:/external_disk
    labels:
      glance.name: BackRest
      glance.icon: di:backrest
      glance.url: http://nasbox.local:9898
      glance.description: BackRest backup manager
    environment:
      - BACKREST_DATA=/data # path for backrest data. restic binary and the database are placed here.
      - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
      - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
      - TZ=Europe/London # set the timezone for the container, used as the timezone for cron jobs.
    restart: unless-stopped
    ports:
      - 9898:9898
networks: {}
