services:
  calibre-web:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/userdata/docker/calibre-web/data:/config
      - /mnt/userdata/books/Library:/calibre-library
      - /mnt/userdata/books/consume:/cwa-book-ingest
    ports:
      - 8083:8083
    restart: always
    labels:
      glance.name: CalibreWeb
      glance.icon: si:calibreweb
      glance.url: http://books.wezzit.org
      glance.description: Books
      glance.id: calibre-web

  koreader-calibre-web-sync:
    restart: always
    ports:
      - 2487:5000
    container_name: koreader
    image: vincentbitter/koreader-calibre-web-sync:latest     
    labels:
      glance.parent: calibre-web
      glance.name: Progress sync plugin
networks: {}
