version: "3.2"
services:
  cloudflared-example:
    image: cloudflare/cloudflared:latest
    labels:
      glance.name: CloudFlareD
      glance.icon: di:cloudflare
      glance.url: https://dash.cloudflare.com
      glance.description: Cloudflare tunnel manager
    network_mode: host
    command: tunnel run
    user: root
    restart: always
    env_file: .env
networks: {}
