services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    tty: true
    restart: unless-stopped
    labels:
      glance.name: Ollama
      glance.icon: di:ollama
      glance.description: LLM wrapper
      glance.id: ollama
      glance.url: http://nasbox.local:6307
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 6307:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    env_file: .env
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    labels:
      glance.parent: ollama
      glance.name: openwebui
volumes:
  ollama: {}
  open-webui: {}
networks: {}
