version: "3"
services:
  db:
    image: postgres:15-alpine
    env_file: .env
    logging:
      driver: none
    restart: unless-stopped
    volumes:
      - /mnt/userdata/docker/wikijs/dbdata:/var/lib/postgresql/data
  wiki:
    image: ghcr.io/requarks/wiki:2
    labels:
      glance.name: WikiJS
      glance.icon: wikijs.png
      glance.url: https://wiki.wezzit.org
      glance.description: Wiki
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    restart: unless-stopped
    ports:
      - 5291:3000
networks: {}
