version: "3.11"
services:
  nextcash:
    image: ghcr.io/sandeep84/next-cash
    restart: unless-stopped
    env_file: .env
    ports:
      - 4129:3000
    labels:
      - homepage.group=Finance
      - homepage.name=NextCash
      - homepage.icon=si-cashapp.svg
      - homepage.href=http://nasbox.local:4129
      - homepage.description=Nextcash account manager
  db:
    image: postgres:15-alpine
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - /mnt/userdata/docker/gnucash/postgres:/var/lib/postgresql/data
networks: {}
