version: "3.11"
services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - /mnt/userdata/docker/gnucash/postgres:/var/lib/postgresql/data
  frontend:
    image: localhost:5000/moneybags-frontend
    env_file: .env
    ports:
      - 4328:4040
  backend:
    image: localhost:5000/moneybags-backend
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - /mnt/userdata/docker/gnucash/rules.txt:/data/rules.txt
      - /mnt/userdata/docker/gnucash/secrets.json:/data/secrets.json
networks: {}
