version: "3.11"
services:
  nextcash:
    image: ghcr.io/sandeep84/next-cash
    labels:
      glance.name: NextCash
      glance.icon: si:cashapp
      glance.url: http://nasbox.local:4129
      glance.description: Finance manager
      glance.id: nextcash
    restart: unless-stopped
    env_file: .env
    ports:
      - 4129:3000
  db:
    image: postgres:15-alpine
    labels:
      glance.parent: nextcash
      glance.name: Database
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - /mnt/userdata/docker/gnucash/postgres:/var/lib/postgresql/data
networks: {}
