version: "3.11"
services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - /mnt/userdata/docker/gnucash/postgres:/var/lib/postgresql/data
  app:
    image: ghcr.io/joshuabach/gnucash-web:main
    restart: always
    env_file: .env
    ports:
      - 4328:8000
volumes:
  db-data: null
networks: {}
