services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    labels:
      - homepage.group=Dashboard
      - homepage.name=DockGE
      - homepage.icon=dockge.png
      - homepage.href=http://nasbox.local:5001
      - homepage.description=Docker manager
    ports:
      # Host Port : Container Port
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/userdata/docker/dockge/data:/app/data
      - /home/sandeep/stacks:/home/sandeep/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/home/sandeep/stacks
networks: {}
